### PR TITLE
Documentation for UseKeys method

### PR DESCRIPTION
**Pull request by brantburnett**

### CODE REVIEW

**Comment by brantburnett** [comment]
@jeffrymorris 

I picked a simple piece of documentation to help with first.  That way you can review my approach, styling, etc, and make sure you're happy with it.

Thanks,
Brant

**Comment by jeffrymorris** [comment]
@brantburnett -

Looks good :)

-Jeff

**Comment by jeffrymorris** [comment]
@brantburnett -

I missed one thing: the README.md just needs to be updated with the link to that doc!

We can also do a final review before release, I can ask our docs people to help out.

Thanks,

Jeff

**Comment by brantburnett** [comment]
K, I'll add the link for that one in the next pull.  Going to do where
clause next, I think.

Brant

On Tue, Oct 20, 2015 at 9:35 PM, Jeffry Morris <notifications@github.com>
wrote:

> @brantburnett <https://github.com/brantburnett> -
>
> I missed one thing: the README.md just needs to be updated with the link
> to that doc!
>
> We can also do a final review before release, I can ask our docs people to
> help out.
>
> Thanks,
>
> Jeff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/couchbaselabs/Linq2Couchbase/pull/66#issuecomment-149753616>
> .
>



-- 
Thanks,
Brant Burnett
CenterEdge Software
(336) 598-5934
http://centeredgesoftware.com

**Pull request merged**
