### PR TITLE
Mutationstate fix

### PR DESCRIPTION
**Pull request by brendon1982**
Updated guard clause on BucketContext.AddToMutationState to match the logic in Couchbase .NET Client library, this was to fix an issue where sometimes the .NET Client Library returned an invalid Token.

### CODE REVIEW

**Comment by brendon1982** [comment]
Now I'm quite confused, the build is failing with this error:

C:\projects\linq2couchbase\Src\Couchbase.Linq.UnitTests.NetCore\Couchbase.Linq.UnitTests.NetCore.xproj(7,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\1.0.4\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
  Build FAILED.

My pull request doesn't in any way touch the Couchbase.Linq.UnitTests.NetCore.xproj file :(

**Comment by brantburnett** [comment]
@jeffrymorris 

I'm not certain, but it looks to me like the build problem is with AppVeyor itself, not these changes.  It's failing to find particular .Net Core files being referenced by the old-style xproj files.

Brant

**Comment by brendon1982** [comment]
Looking at the build history I see the last successful build was 3 months ago, maybe AppVeyor has changed the environment since then?

**Comment by MikeGoldsmith** [comment]
Hi @brendon1982 

I've fixed the problem with AppVeyor not being able to successfully build the solution. If you pull my changes into your branch it should build and then we can merge.

Thanks

**Comment by brendon1982** [comment]
Yay all sorted ;D

**Pull request merged**
