### PR TITLE
Update the NetStandard project to the new csproj format

### LINKED ISSUE #181: Migrating to new csproj format
Hi all, I'm using Linq2Couchbase by direct referencing it in a netcoreapp 1.1 with VSCode on a Mac.

Since Microsoft released the final version, some changes has to be made to Couchbase.Linq.NetStandard.csproj and finaly we'll no need to use that project.json (wich do not permits link as csproj do).

I've already done it:
https://github.com/FernandoMorais/Linq2Couchbase/tree/feature/netcoreapp1.1

How could I make the PR to integrate that changes?
Do I need to follow some procedure ou just make the PR?

Thanks!

### PR DESCRIPTION
**Pull request by FernandoMorais**
# Motivation
Move the Couchbase.Linq.NetStandard project to the final release tools, wich will allow build the project into VS 2017, VS Code and CLI.

# Modifications
- removed: project.json
- updated:  Couchbase.Linq.NetStandard.csproj

# Results
With the new csproj model we'll be able to use the same project definitions across platforms, allowing compile with links, wich wasn't possible in project.json.
resolve #181

### CODE REVIEW

**Comment by brantburnett** [comment]
@FernandoMorais 

Thanks for the pull.  I've discussed this some with @jeffrymorris, and we think we're going to wait to merge this for a while.  We want to keep the Couchbase SDK and Linq2Couchbase on the same version of VS for simplicity.  And it will be a bit before we can switch the SDK to VS2015 due to continuous integration requirements.

That said, Linq2Couchbase can still be consumed by an app in VS2017.  Just working directly in Linq2Couchbase and building it will require VS2015 for the time being.  But the output binary should be functional across versions.

Brant

**Comment by jeffrymorris** [comment]
@FernandoMorais -

Thanks for the contribution! We currently are not ready internally to convert over the projects over to VS2017 since it involves the SDK (github.com/couchbase/couchbase-net-client), our internal QE infrastructure, and AppVeyour.

In the next couple of weeks we will convert over these over to VS2017 project structure. After that, we'll merge this PR once everything else has been upgraded.

Thanks,

Jeff

**Comment by FernandoMorais** [comment]
Nice @brantburnett! 

I'll continue to work using my fork, which I think will help you in a future migration! 

Besides that I really want to say that I am in love with Couchbase... Working in an local P2P application (master - slave, no Internet first). All you are doing a fabulous work! 

Thanks!

**Comment by MikeGoldsmith** [comment]
Hi @FernandoMorais - just wanted to let you know we ended up doing this ourselves after merging the work on the main .NET client in #181. Thanks for the PR, we def used it as a reference point but had some additional challenges to overcome.

**Pull request closed without merging**
