### PR TITLE
Added support to QueryRequest Timeouts

### PR DESCRIPTION
**Pull request by badavid85**

### CODE REVIEW

**Comment by MikeGoldsmith** [comment]
Looks great @badavid85  - thank you for the contribution

**Comment by badavid85** [comment]
When will the new nuget pkg be available (1.4.1) ?

**Comment by jeffrymorris** [comment]
@badavid85 - we will do a build/release this Monday or Weds.

**Comment by jeffrymorris** [comment]
@badavid85 https://www.nuget.org/packages/Linq2Couchbase/1.4.1

**Pull request merged**
